version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular-devkit/schematics"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.0.5
    - 4.0.6
