//just a snapshot of the anti mangle options i use for ghPages.
// manually hacked into node_modules/@angular/cli/models/webpack-configs/production.js
// Uglify options

{reserved: ['grid',
  'weights',
  'calcParams',
  'addChemicalsParams',
  'whenGt',
  'whenLt',
  'value',
  'value2',
  'whenGe',
  'whenLe',
  'and',
  'a',
  'b',
  'greater',
  'smallerZero',
  'wrapAround',
  'inBetween',
  'fluid',
  'columnOffset',
  'rowOffset',
  'yIndex',
  'xIndex',
  'cellValue',
  'calcWeightedSum',
  'sum',
  'calcNextA',
  'dA',
  'dB',
  'laplaceA',
  'laplaceB',
  'abb',
  'f',
  'fT',
  'k',
  'kT',
  'nextA',
  'calcFluidBToAdd',
  'x',
  'xNormed',
  'y',
  'yNormed',
  'radius',
  'isFluidB',
  'i',
  'j',
  'radPos',
  'isInRadiusAndFluidB',
  'fluidBToAdd',
  'dynkillfeed',
  'addChems'
],}
